@startuml
set namespaceSeparator ::

abstract class "shikimoriapp::feature::data::datasources::anime::anime_remote_data_source.dart::AnimeRemoteDataSource" {
  +dynamic getAnimes()
  +dynamic getAnimesByName()
  +dynamic getAnimeById()
  +dynamic getVideos()
  +dynamic getScreenshots()
  +dynamic getRelatedAnime()
}

class "shikimoriapp::feature::data::datasources::anime::anime_remote_data_source_impl.dart::AnimeRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getAnimeById()
  +dynamic getAnimes()
  +dynamic getVideos()
  +dynamic getScreenshots()
  +dynamic getRelatedAnime()
  +dynamic getAnimesByName()
}

"shikimoriapp::feature::data::datasources::anime::anime_remote_data_source_impl.dart::AnimeRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::anime::anime_remote_data_source.dart::AnimeRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::anime::anime_remote_data_source_impl.dart::AnimeRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::character::character_remote_data_source.dart::CharacterRemoteDataSource" {
  +dynamic getCharacterById()
}

class "shikimoriapp::feature::data::datasources::character::character_remote_data_source_impl.dart::CharacterRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getCharacterById()
}

"shikimoriapp::feature::data::datasources::character::character_remote_data_source_impl.dart::CharacterRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::character::character_remote_data_source.dart::CharacterRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::character::character_remote_data_source_impl.dart::CharacterRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source.dart::CreditionalRemoteDataSource" {
  +dynamic getCreditionals()
}

class "shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source_impl.dart::CreditionalRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getCreditionals()
}

"shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source_impl.dart::CreditionalRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source.dart::CreditionalRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source_impl.dart::CreditionalRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::manga::manga_remote_data_source.dart::MangaRemoteDataSource" {
  +dynamic getAnimes()
  +dynamic getAnimeById()
}

class "shikimoriapp::feature::data::datasources::manga::manga_remote_data_source_impl.dart::MangaRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getAnimes()
  +dynamic getAnimeById()
}

"shikimoriapp::feature::data::datasources::manga::manga_remote_data_source_impl.dart::MangaRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::manga::manga_remote_data_source.dart::MangaRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::manga::manga_remote_data_source_impl.dart::MangaRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::related::related_remote_data_source.dart::RelatedRemoteDataSource" {
  +dynamic getRelated()
}

class "shikimoriapp::feature::data::datasources::related::related_remote_data_source_impl.dart::RelatedRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getRelated()
}

"shikimoriapp::feature::data::datasources::related::related_remote_data_source_impl.dart::RelatedRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::related::related_remote_data_source.dart::RelatedRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::related::related_remote_data_source_impl.dart::RelatedRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::token::token_local_data_source.dart::TokenLocalDataSource" {
  +dynamic saveAccessToken()
  +dynamic saveRefreshToken()
}

class "shikimoriapp::feature::data::datasources::token::token_local_data_source_impl.dart::TokenLocalDataSourceImpl" {
  +FlutterSecureStorage storage
  +dynamic saveAccessToken()
  +dynamic saveRefreshToken()
}

"shikimoriapp::feature::data::datasources::token::token_local_data_source_impl.dart::TokenLocalDataSourceImpl" o-- "flutter_secure_storage::flutter_secure_storage.dart::FlutterSecureStorage"
"shikimoriapp::feature::data::datasources::token::token_local_data_source.dart::TokenLocalDataSource" <|-- "shikimoriapp::feature::data::datasources::token::token_local_data_source_impl.dart::TokenLocalDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source.dart::UserAuthRemoteDataSource" {
  +dynamic getAccessToken()
  +dynamic refreshAccessToken()
}

class "shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source_impl.dart::UserAuthRemoteDataSourceImpl" {
  +Dio dio
  +dynamic getAccessToken()
  +dynamic refreshAccessToken()
}

"shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source_impl.dart::UserAuthRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source.dart::UserAuthRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source_impl.dart::UserAuthRemoteDataSourceImpl"

abstract class "shikimoriapp::feature::data::datasources::user_rate::user_rate_remote_data_source.dart::UserRateRemoteDataSource" {
  +dynamic getUserRateById()
  +dynamic addAnimeInUserRates()
  +dynamic getAllUserRates()
}

class "shikimoriapp::feature::data::datasources::user_rate::user_rate_remote_data_source_impl.dart::UserRateRemoteDataSourceImpl" {
  +Dio dio
  +dynamic addAnimeInUserRates()
  +dynamic getUserRateById()
  +dynamic getAllUserRates()
}

"shikimoriapp::feature::data::datasources::user_rate::user_rate_remote_data_source_impl.dart::UserRateRemoteDataSourceImpl" o-- "dio::src::dio.dart::Dio"
"shikimoriapp::feature::data::datasources::user_rate::user_rate_remote_data_source.dart::UserRateRemoteDataSource" <|-- "shikimoriapp::feature::data::datasources::user_rate::user_rate_remote_data_source_impl.dart::UserRateRemoteDataSourceImpl"

class "shikimoriapp::feature::data::models::anime::anime.dart::AnimeModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::anime::anime.dart::Anime" <|-- "shikimoriapp::feature::data::models::anime::anime.dart::AnimeModel"

class "shikimoriapp::feature::data::models::anime::image.dart::ImageModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::anime::image.dart::Image" <|-- "shikimoriapp::feature::data::models::anime::image.dart::ImageModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::AnimeDetailsModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::AnimeDetails" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::AnimeDetailsModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::GenreModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::Genre" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::GenreModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::ImageModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::Image" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::ImageModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::RatesScoresStatModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::RatesScoresStat" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::RatesScoresStatModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::RatesStatusesStatModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::RatesStatusesStat" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::RatesStatusesStatModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::ScreenshotModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::Screenshot" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::ScreenshotModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::StudioModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::Studio" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::StudioModel"

class "shikimoriapp::feature::data::models::anime_details::anime_details.dart::VideoModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::anime_details::anime_details.dart::Video" <|-- "shikimoriapp::feature::data::models::anime_details::anime_details.dart::VideoModel"

class "shikimoriapp::feature::data::models::character::character.dart::CharacterModel" {
}

"shikimoriapp::feature::domain::entities::character::character.dart::Character" <|-- "shikimoriapp::feature::data::models::character::character.dart::CharacterModel"

class "shikimoriapp::feature::data::models::character::character.dart::AnimeModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::character::character.dart::Anime" <|-- "shikimoriapp::feature::data::models::character::character.dart::AnimeModel"

class "shikimoriapp::feature::data::models::character::character.dart::SeyuModel" {
}

"shikimoriapp::feature::domain::entities::character::character.dart::Seyu" <|-- "shikimoriapp::feature::data::models::character::character.dart::SeyuModel"

class "shikimoriapp::feature::data::models::character::character.dart::ImageModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::character::character.dart::Image" <|-- "shikimoriapp::feature::data::models::character::character.dart::ImageModel"

class "shikimoriapp::feature::data::models::creditional::creditional.dart::CreditionalModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::creditional::creditional.dart::Creditional" <|-- "shikimoriapp::feature::data::models::creditional::creditional.dart::CreditionalModel"

class "shikimoriapp::feature::data::models::creditional::creditional.dart::ImageModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::creditional::creditional.dart::Image" <|-- "shikimoriapp::feature::data::models::creditional::creditional.dart::ImageModel"

class "shikimoriapp::feature::data::models::manga::manga.dart::MangaModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::manga::manga.dart::Manga" <|-- "shikimoriapp::feature::data::models::manga::manga.dart::MangaModel"

class "shikimoriapp::feature::data::models::manga::manga.dart::ImageModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::manga::image.dart::Image" <|-- "shikimoriapp::feature::data::models::manga::manga.dart::ImageModel"

class "shikimoriapp::feature::data::models::related::related.dart::RelatedModel" {
}

"shikimoriapp::feature::domain::entities::related::related.dart::Related" <|-- "shikimoriapp::feature::data::models::related::related.dart::RelatedModel"

class "shikimoriapp::feature::data::models::user_auth::user_auth.dart::UserAuthModel" {
  +List<Object?> props
}

"shikimoriapp::feature::domain::entities::user_auth::user_auth.dart::UserAuth" <|-- "shikimoriapp::feature::data::models::user_auth::user_auth.dart::UserAuthModel"

class "shikimoriapp::feature::data::models::user_rate::user_rate.dart::UserRateModel" {
  +List<Object?> props
  +Map<String, dynamic> toJson()
}

"shikimoriapp::feature::domain::entities::user_rate::user_rate.dart::UserRate" <|-- "shikimoriapp::feature::data::models::user_rate::user_rate.dart::UserRateModel"

class "shikimoriapp::feature::data::repository::anime_repository_impl.dart::AnimeRepositoryImpl" {
  +AnimeRemoteDataSource animeRemoteDataSource
  +dynamic getAnimeById()
  +dynamic getAnimes()
  -dynamic _getAnimeById()
  -dynamic _getAnimes()
  +dynamic getVideos()
  -dynamic _getVideos()
  +dynamic getScreenshots()
  -dynamic _getScreenshots()
  +dynamic getAnimesByName()
  -dynamic _getAnimesByName()
}

"shikimoriapp::feature::data::repository::anime_repository_impl.dart::AnimeRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::anime::anime_remote_data_source.dart::AnimeRemoteDataSource"
"shikimoriapp::feature::domain::repositories::anime_repository.dart::AnimeRepository" <|-- "shikimoriapp::feature::data::repository::anime_repository_impl.dart::AnimeRepositoryImpl"

class "shikimoriapp::feature::data::repository::character_repository_impl.dart::CharacterRepositoryImpl" {
  +CharacterRemoteDataSource characterRemoteDataSource
  +dynamic getCharacterById()
  -dynamic _getCharacterById()
}

"shikimoriapp::feature::data::repository::character_repository_impl.dart::CharacterRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::character::character_remote_data_source.dart::CharacterRemoteDataSource"
"shikimoriapp::feature::domain::repositories::character_repository.dart::CharacterRepository" <|-- "shikimoriapp::feature::data::repository::character_repository_impl.dart::CharacterRepositoryImpl"

class "shikimoriapp::feature::data::repository::creditional_repository_impl.dart::CreditionalRepositoryImpl" {
  +CreditionalRemoteDataSource creditional
  +dynamic getCreditionals()
  -dynamic _getCreditionals()
}

"shikimoriapp::feature::data::repository::creditional_repository_impl.dart::CreditionalRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::creditional::creditional_remote_data_source.dart::CreditionalRemoteDataSource"
"shikimoriapp::feature::domain::repositories::creditional_repository.dart::CreditionalRepository" <|-- "shikimoriapp::feature::data::repository::creditional_repository_impl.dart::CreditionalRepositoryImpl"

class "shikimoriapp::feature::data::repository::refresh_access_token_repository_impl.dart::RefreshAccessTokenRepositoryImpl" {
  +UserAuthRemoteDataSource tokenRemoteDataSource
  +dynamic refreshAccessToken()
  -dynamic _auth()
}

"shikimoriapp::feature::data::repository::refresh_access_token_repository_impl.dart::RefreshAccessTokenRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source.dart::UserAuthRemoteDataSource"
"shikimoriapp::feature::domain::repositories::refresh_access_token_repository.dart::RefreshAccessTokenRepository" <|-- "shikimoriapp::feature::data::repository::refresh_access_token_repository_impl.dart::RefreshAccessTokenRepositoryImpl"

class "shikimoriapp::feature::data::repository::refresh_token_repository_impl.dart::SaveRefreshTokenRepositoryImpl" {
  +TokenLocalDataSource tokenLocalDataSource
  +dynamic saveRefreshToken()
  -dynamic _saveRefreshToken()
}

"shikimoriapp::feature::data::repository::refresh_token_repository_impl.dart::SaveRefreshTokenRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::token::token_local_data_source.dart::TokenLocalDataSource"
"shikimoriapp::feature::domain::repositories::save_tokens_repository.dart::SaveRefreshTokenRepository" <|-- "shikimoriapp::feature::data::repository::refresh_token_repository_impl.dart::SaveRefreshTokenRepositoryImpl"

class "shikimoriapp::feature::data::repository::related_repository_impl.dart::RelatedRepositoryImpl" {
  +RelatedRemoteDataSource relatedRemoteDataSource
  +dynamic getRelated()
  -dynamic _getRelated()
}

"shikimoriapp::feature::data::repository::related_repository_impl.dart::RelatedRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::related::related_remote_data_source.dart::RelatedRemoteDataSource"
"shikimoriapp::feature::domain::repositories::related_repository.dart::RelatedRepository" <|-- "shikimoriapp::feature::data::repository::related_repository_impl.dart::RelatedRepositoryImpl"

class "shikimoriapp::feature::data::repository::save_access_token_repository_impl.dart::SaveAccessTokenRepositoryImpl" {
  +TokenLocalDataSource tokenLocalDataSource
  +dynamic saveAccessToken()
  -dynamic _saveAccessToken()
}

"shikimoriapp::feature::data::repository::save_access_token_repository_impl.dart::SaveAccessTokenRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::token::token_local_data_source.dart::TokenLocalDataSource"
"shikimoriapp::feature::domain::repositories::save_tokens_repository.dart::SaveAccessTokenRepository" <|-- "shikimoriapp::feature::data::repository::save_access_token_repository_impl.dart::SaveAccessTokenRepositoryImpl"

class "shikimoriapp::feature::data::repository::user_auth_repository_impl.dart::GetAccessTokenRepositoryImpl" {
  +UserAuthRemoteDataSource tokenRemoteDataSource
  +dynamic getAccessToken()
  -dynamic _auth()
}

"shikimoriapp::feature::data::repository::user_auth_repository_impl.dart::GetAccessTokenRepositoryImpl" o-- "shikimoriapp::feature::data::datasources::user_auth::user_auth_remote_data_source.dart::UserAuthRemoteDataSource"
"shikimoriapp::feature::domain::repositories::access_token_repository.dart::GetAccessTokenRepository" <|-- "shikimoriapp::feature::data::repository::user_auth_repository_impl.dart::GetAccessTokenRepositoryImpl"


@enduml