classDiagram
class ApiClient
ApiClient : +grant AuthorizationCodeGrant
ApiClient o-- AuthorizationCodeGrant
ApiClient : +authorizationUrl Uri
ApiClient : +shikimoriUrl$ String
ApiClient : -_host$ String
ApiClient : -_hostV2$ String
ApiClient : +redirectUri Uri
ApiClient : +authorizationEndpoint Uri
ApiClient : +tokenEndpoint Uri
ApiClient : -_identifier$ String
ApiClient : -_secret$ String
ApiClient : +code String
ApiClient : -_dio Dio
ApiClient o-- Dio
ApiClient : +accessToken String
ApiClient : -_singleton$ ApiClient
ApiClient o-- ApiClient
ApiClient : +getAccessToken() dynamic
ApiClient : +getCreditionals() dynamic
ApiClient : +addAnimeInRateList() dynamic
ApiClient : +getAnimeRateList() dynamic
ApiClient : +getAnimes() dynamic
ApiClient : +getAnimeById() dynamic

class ServerException
Exception <|.. ServerException

class ClientException
Exception <|.. ClientException

class AuthException
Exception <|.. AuthException

class SaveException
Exception <|.. SaveException

class Failure
<<abstract>> Failure
Failure : +props List~Object?~
Equatable <|-- Failure

class ServerFailure
Failure <|-- ServerFailure

class LocalFailure
Failure <|-- LocalFailure

class AuthFailure
Failure <|-- AuthFailure

class EnumValues
EnumValues : +map Map~String, T~
EnumValues : +reverseMap Map~T, String~
EnumValues : +reverse Map~T, String~

class Debouncer
Debouncer : +duration Duration
Debouncer : +action void Function?
Debouncer o-- void Function
Debouncer : -_timer Timer?
Debouncer o-- Timer
Debouncer : +run() dynamic

class SText
SText : +text String
SText : +toString() String

class Url
Url : +id int
Url : +toString() String
SText <|-- Url

class AppImages
<<abstract>> AppImages
AppImages : +loagingPageBg$ String
AppImages : +missing$ String
AppImages : +loadingAnimation$ String

class UseCase
<<abstract>> UseCase
UseCase : +call()* dynamic

class AnimeCardWidget
AnimeCardWidget : +imageUrl String
AnimeCardWidget : +title String
AnimeCardWidget : +score String
AnimeCardWidget : +episodes int
AnimeCardWidget : +animeId int
AnimeCardWidget : +build() Widget
StatelessWidget <|-- AnimeCardWidget

class CustomLoadingBar
CustomLoadingBar : +build() Widget
StatelessWidget <|-- CustomLoadingBar

class HeadlineButton
HeadlineButton : +title String
HeadlineButton : +child Widget
HeadlineButton o-- Widget
HeadlineButton : +height double?
HeadlineButton : +onPress dynamic Function
HeadlineButton o-- dynamic Function
HeadlineButton : +build() Widget
StatelessWidget <|-- HeadlineButton

class HeadlineWidget
HeadlineWidget : +title String
HeadlineWidget : +height double?
HeadlineWidget : +build() Widget
StatelessWidget <|-- HeadlineWidget

class HtmlDescriptionWidget
HtmlDescriptionWidget : +data String?
HtmlDescriptionWidget : +build() Widget
StatelessWidget <|-- HtmlDescriptionWidget

class LoadingCard
LoadingCard : +build() Widget
StatelessWidget <|-- LoadingCard

class MangaCardWidget
MangaCardWidget : +imageUrl String
MangaCardWidget : +title String
MangaCardWidget : +score String
MangaCardWidget : +episodes int
MangaCardWidget : +animeId int
MangaCardWidget : +build() Widget
StatelessWidget <|-- MangaCardWidget

class SearchDelegateImpl
SearchDelegateImpl : +buildActions() List<Widget>?
SearchDelegateImpl : +buildLeading() Widget?
SearchDelegateImpl : +buildResults() Widget
SearchDelegateImpl : +buildSuggestions() Widget
SearchDelegate <|-- SearchDelegateImpl

class _SearchBuilder
_SearchBuilder : +query String
_SearchBuilder : +build() Widget
StatelessWidget <|-- _SearchBuilder

class AnimeRemoteDataSource
<<abstract>> AnimeRemoteDataSource
AnimeRemoteDataSource : +getAnimes()* dynamic
AnimeRemoteDataSource : +getAnimesByName()* dynamic
AnimeRemoteDataSource : +getAnimeById()* dynamic
AnimeRemoteDataSource : +getVideos()* dynamic
AnimeRemoteDataSource : +getScreenshots()* dynamic
AnimeRemoteDataSource : +getRelatedAnime()* dynamic

class AnimeRemoteDataSourceImpl
AnimeRemoteDataSourceImpl : +dio Dio
AnimeRemoteDataSourceImpl o-- Dio
AnimeRemoteDataSourceImpl : +getAnimeById() dynamic
AnimeRemoteDataSourceImpl : +getAnimes() dynamic
AnimeRemoteDataSourceImpl : +getVideos() dynamic
AnimeRemoteDataSourceImpl : +getScreenshots() dynamic
AnimeRemoteDataSourceImpl : +getRelatedAnime() dynamic
AnimeRemoteDataSourceImpl : +getAnimesByName() dynamic
AnimeRemoteDataSource <|.. AnimeRemoteDataSourceImpl

class CharacterRemoteDataSource
<<abstract>> CharacterRemoteDataSource
CharacterRemoteDataSource : +getCharacterById()* dynamic

class CharacterRemoteDataSourceImpl
CharacterRemoteDataSourceImpl : +dio Dio
CharacterRemoteDataSourceImpl o-- Dio
CharacterRemoteDataSourceImpl : +getCharacterById() dynamic
CharacterRemoteDataSource <|.. CharacterRemoteDataSourceImpl

class CreditionalRemoteDataSource
<<abstract>> CreditionalRemoteDataSource
CreditionalRemoteDataSource : +getCreditionals()* dynamic

class CreditionalRemoteDataSourceImpl
CreditionalRemoteDataSourceImpl : +dio Dio
CreditionalRemoteDataSourceImpl o-- Dio
CreditionalRemoteDataSourceImpl : +getCreditionals() dynamic
CreditionalRemoteDataSource <|.. CreditionalRemoteDataSourceImpl

class MangaRemoteDataSource
<<abstract>> MangaRemoteDataSource
MangaRemoteDataSource : +getAnimes()* dynamic
MangaRemoteDataSource : +getAnimeById()* dynamic

class MangaRemoteDataSourceImpl
MangaRemoteDataSourceImpl : +dio Dio
MangaRemoteDataSourceImpl o-- Dio
MangaRemoteDataSourceImpl : +getAnimes() dynamic
MangaRemoteDataSourceImpl : +getAnimeById() dynamic
MangaRemoteDataSource <|.. MangaRemoteDataSourceImpl

class RelatedRemoteDataSource
<<abstract>> RelatedRemoteDataSource
RelatedRemoteDataSource : +getRelated()* dynamic

class RelatedRemoteDataSourceImpl
RelatedRemoteDataSourceImpl : +dio Dio
RelatedRemoteDataSourceImpl o-- Dio
RelatedRemoteDataSourceImpl : +getRelated() dynamic
RelatedRemoteDataSource <|.. RelatedRemoteDataSourceImpl

class TokenLocalDataSource
<<abstract>> TokenLocalDataSource
TokenLocalDataSource : +saveAccessToken()* dynamic
TokenLocalDataSource : +saveRefreshToken()* dynamic

class TokenLocalDataSourceImpl
TokenLocalDataSourceImpl : +storage FlutterSecureStorage
TokenLocalDataSourceImpl o-- FlutterSecureStorage
TokenLocalDataSourceImpl : +saveAccessToken() dynamic
TokenLocalDataSourceImpl : +saveRefreshToken() dynamic
TokenLocalDataSource <|.. TokenLocalDataSourceImpl

class UserAuthRemoteDataSource
<<abstract>> UserAuthRemoteDataSource
UserAuthRemoteDataSource : +getAccessToken()* dynamic
UserAuthRemoteDataSource : +refreshAccessToken()* dynamic

class UserAuthRemoteDataSourceImpl
UserAuthRemoteDataSourceImpl : +dio Dio
UserAuthRemoteDataSourceImpl o-- Dio
UserAuthRemoteDataSourceImpl : +getAccessToken() dynamic
UserAuthRemoteDataSourceImpl : +refreshAccessToken() dynamic
UserAuthRemoteDataSource <|.. UserAuthRemoteDataSourceImpl

class UserRateRemoteDataSource
<<abstract>> UserRateRemoteDataSource
UserRateRemoteDataSource : +getUserRateById()* dynamic
UserRateRemoteDataSource : +addAnimeInUserRates()* dynamic
UserRateRemoteDataSource : +getAllUserRates()* dynamic

class UserRateRemoteDataSourceImpl
UserRateRemoteDataSourceImpl : +dio Dio
UserRateRemoteDataSourceImpl o-- Dio
UserRateRemoteDataSourceImpl : +addAnimeInUserRates() dynamic
UserRateRemoteDataSourceImpl : +getUserRateById() dynamic
UserRateRemoteDataSourceImpl : +getAllUserRates() dynamic
UserRateRemoteDataSource <|.. UserRateRemoteDataSourceImpl

class AnimeModel
AnimeModel : +props List~Object?~
AnimeModel : +toJson() Map<String, dynamic>
Anime <|-- AnimeModel

class ImageModel
ImageModel : +props List~Object?~
ImageModel : +toJson() Map<String, dynamic>
Image <|-- ImageModel

class AnimeDetailsModel
AnimeDetailsModel : +props List~Object?~
AnimeDetails <|-- AnimeDetailsModel

class GenreModel
GenreModel : +props List~Object?~
Genre <|-- GenreModel

class ImageModel
ImageModel : +props List~Object?~
ImageModel : +toJson() Map<String, dynamic>
Image <|-- ImageModel

class RatesScoresStatModel
RatesScoresStatModel : +props List~Object?~
RatesScoresStat <|-- RatesScoresStatModel

class RatesStatusesStatModel
RatesStatusesStatModel : +props List~Object?~
RatesStatusesStat <|-- RatesStatusesStatModel

class ScreenshotModel
ScreenshotModel : +props List~Object?~
Screenshot <|-- ScreenshotModel

class StudioModel
StudioModel : +props List~Object?~
Studio <|-- StudioModel

class VideoModel
VideoModel : +props List~Object?~
Video <|-- VideoModel

class CharacterModel
Character <|-- CharacterModel

class AnimeModel
AnimeModel : +props List~Object?~
Anime <|-- AnimeModel

class SeyuModel
Seyu <|-- SeyuModel

class ImageModel
ImageModel : +props List~Object?~
Image <|-- ImageModel

class CreditionalModel
CreditionalModel : +props List~Object?~
CreditionalModel : +toJson() Map<String, dynamic>
Creditional <|-- CreditionalModel

class ImageModel
ImageModel : +props List~Object?~
ImageModel : +toJson() Map<String, dynamic>
Image <|-- ImageModel

class MangaModel
MangaModel : +props List~Object?~
Manga <|-- MangaModel

class ImageModel
ImageModel : +props List~Object?~
ImageModel : +toJson() Map<String, dynamic>
Image <|-- ImageModel

class RelatedModel
Related <|-- RelatedModel

class UserAuthModel
UserAuthModel : +props List~Object?~
UserAuth <|-- UserAuthModel

class UserRateModel
UserRateModel : +props List~Object?~
UserRateModel : +toJson() Map<String, dynamic>
UserRate <|-- UserRateModel

class AnimeRepositoryImpl
AnimeRepositoryImpl : +animeRemoteDataSource AnimeRemoteDataSource
AnimeRepositoryImpl o-- AnimeRemoteDataSource
AnimeRepositoryImpl : +getAnimeById() dynamic
AnimeRepositoryImpl : +getAnimes() dynamic
AnimeRepositoryImpl : -_getAnimeById() dynamic
AnimeRepositoryImpl : -_getAnimes() dynamic
AnimeRepositoryImpl : +getVideos() dynamic
AnimeRepositoryImpl : -_getVideos() dynamic
AnimeRepositoryImpl : +getScreenshots() dynamic
AnimeRepositoryImpl : -_getScreenshots() dynamic
AnimeRepositoryImpl : +getAnimesByName() dynamic
AnimeRepositoryImpl : -_getAnimesByName() dynamic
AnimeRepository <|.. AnimeRepositoryImpl

class CharacterRepositoryImpl
CharacterRepositoryImpl : +characterRemoteDataSource CharacterRemoteDataSource
CharacterRepositoryImpl o-- CharacterRemoteDataSource
CharacterRepositoryImpl : +getCharacterById() dynamic
CharacterRepositoryImpl : -_getCharacterById() dynamic
CharacterRepository <|.. CharacterRepositoryImpl

class CreditionalRepositoryImpl
CreditionalRepositoryImpl : +creditional CreditionalRemoteDataSource
CreditionalRepositoryImpl o-- CreditionalRemoteDataSource
CreditionalRepositoryImpl : +getCreditionals() dynamic
CreditionalRepositoryImpl : -_getCreditionals() dynamic
CreditionalRepository <|.. CreditionalRepositoryImpl

class RefreshAccessTokenRepositoryImpl
RefreshAccessTokenRepositoryImpl : +tokenRemoteDataSource UserAuthRemoteDataSource
RefreshAccessTokenRepositoryImpl o-- UserAuthRemoteDataSource
RefreshAccessTokenRepositoryImpl : +refreshAccessToken() dynamic
RefreshAccessTokenRepositoryImpl : -_auth() dynamic
RefreshAccessTokenRepository <|.. RefreshAccessTokenRepositoryImpl

class SaveRefreshTokenRepositoryImpl
SaveRefreshTokenRepositoryImpl : +tokenLocalDataSource TokenLocalDataSource
SaveRefreshTokenRepositoryImpl o-- TokenLocalDataSource
SaveRefreshTokenRepositoryImpl : +saveRefreshToken() dynamic
SaveRefreshTokenRepositoryImpl : -_saveRefreshToken() dynamic
SaveRefreshTokenRepository <|.. SaveRefreshTokenRepositoryImpl

class RelatedRepositoryImpl
RelatedRepositoryImpl : +relatedRemoteDataSource RelatedRemoteDataSource
RelatedRepositoryImpl o-- RelatedRemoteDataSource
RelatedRepositoryImpl : +getRelated() dynamic
RelatedRepositoryImpl : -_getRelated() dynamic
RelatedRepository <|.. RelatedRepositoryImpl

class SaveAccessTokenRepositoryImpl
SaveAccessTokenRepositoryImpl : +tokenLocalDataSource TokenLocalDataSource
SaveAccessTokenRepositoryImpl o-- TokenLocalDataSource
SaveAccessTokenRepositoryImpl : +saveAccessToken() dynamic
SaveAccessTokenRepositoryImpl : -_saveAccessToken() dynamic
SaveAccessTokenRepository <|.. SaveAccessTokenRepositoryImpl

class GetAccessTokenRepositoryImpl
GetAccessTokenRepositoryImpl : +tokenRemoteDataSource UserAuthRemoteDataSource
GetAccessTokenRepositoryImpl o-- UserAuthRemoteDataSource
GetAccessTokenRepositoryImpl : +getAccessToken() dynamic
GetAccessTokenRepositoryImpl : -_auth() dynamic
GetAccessTokenRepository <|.. GetAccessTokenRepositoryImpl

class Anime
Anime : +id int
Anime : +name String
Anime : +russian String?
Anime : +image Image?
Anime o-- Image
Anime : +url String?
Anime : +kind String?
Anime : +score String?
Anime : +status String?
Anime : +episodes int?
Anime : +episodesAired int?
Anime : +airedOn DateTime?
Anime : +releasedOn DateTime?
Anime : +props List~Object?~
Equatable <|-- Anime

class Image
Image : +original String
Image : +preview String
Image : +x96 String
Image : +x48 String
Image : +props List~Object?~
Equatable <|-- Image

class Kind
Kind : +kindName String
Kind : +props List~Object?~
Equatable <|-- Kind

class Status
Status : +statusName String
Status : +props List~Object?~
Equatable <|-- Status

class AnimeDetails
AnimeDetails : +id int?
AnimeDetails : +name String?
AnimeDetails : +russian String?
AnimeDetails : +image Image?
AnimeDetails o-- Image
AnimeDetails : +url String?
AnimeDetails : +kind String?
AnimeDetails : +score String?
AnimeDetails : +status String?
AnimeDetails : +episodes int?
AnimeDetails : +episodesAired int?
AnimeDetails : +airedOn DateTime?
AnimeDetails : +releasedOn DateTime?
AnimeDetails : +rating String?
AnimeDetails : +english List~String?~
AnimeDetails : +japanese List~String?~
AnimeDetails : +synonyms List~String?~
AnimeDetails : +licenseNameRu dynamic
AnimeDetails : +duration int?
AnimeDetails : +description String?
AnimeDetails : +descriptionHtml String?
AnimeDetails : +descriptionSource dynamic
AnimeDetails : +franchise String?
AnimeDetails : +favoured bool?
AnimeDetails : +anons bool?
AnimeDetails : +ongoing bool?
AnimeDetails : +threadId int?
AnimeDetails : +topicId int?
AnimeDetails : +myanimelistId int?
AnimeDetails : +ratesScoresStats List~RatesScoresStat?~
AnimeDetails : +ratesStatusesStats List~RatesStatusesStat?~
AnimeDetails : +updatedAt DateTime?
AnimeDetails : +nextEpisodeAt dynamic
AnimeDetails : +fansubbers List~String?~
AnimeDetails : +fandubbers List~String?~
AnimeDetails : +licensors List~dynamic~
AnimeDetails : +genres List~Genre?~
AnimeDetails : +studios List~Studio?~
AnimeDetails : +videos List~Video?~
AnimeDetails : +screenshots List~Screenshot?~
AnimeDetails : +userRate dynamic
AnimeDetails : +props List~Object?~
Equatable <|-- AnimeDetails

class Genre
Genre : +id int?
Genre : +name String?
Genre : +russian String?
Genre : +kind String?
Genre : +props List~Object?~
Equatable <|-- Genre

class Image
Image : +original String
Image : +preview String
Image : +x96 String
Image : +x48 String
Image : +props List~Object?~
Equatable <|-- Image

class RatesScoresStat
RatesScoresStat : +name int
RatesScoresStat : +value int
RatesScoresStat : +props List~Object?~
Equatable <|-- RatesScoresStat

class RatesStatusesStat
RatesStatusesStat : +name String
RatesStatusesStat : +value int
RatesStatusesStat : +props List~Object?~
Equatable <|-- RatesStatusesStat

class Screenshot
Screenshot : +original String
Screenshot : +preview String
Screenshot : +props List~Object?~
Equatable <|-- Screenshot

class Studio
Studio : +id int?
Studio : +name String?
Studio : +filteredName String?
Studio : +real bool?
Studio : +image String?
Studio : +props List~Object?~
Equatable <|-- Studio

class Video
Video : +id int
Video : +url String
Video : +imageUrl String
Video : +playerUrl String
Video : +name String
Video : +kind String
Video : +hosting String
Video : +props List~Object?~
Equatable <|-- Video

class Character
Character : +id int?
Character : +name String?
Character : +russian String?
Character : +image Image?
Character o-- Image
Character : +url String?
Character : +altname dynamic
Character : +japanese String?
Character : +description dynamic
Character : +descriptionHtml String?
Character : +descriptionSource dynamic
Character : +favoured bool?
Character : +threadId int?
Character : +topicId int?
Character : +updatedAt DateTime?
Character : +seyu List~Seyu~?
Character : +animes List~Anime~?
Character : +mangas List~dynamic~?
Character : +props List~Object?~
Equatable <|-- Character

class Anime
Anime : +id int
Anime : +name String
Anime : +russian String
Anime : +image Image
Anime o-- Image
Anime : +url String
Anime : +kind String
Anime : +score String
Anime : +status String
Anime : +episodes int
Anime : +episodesAired int
Anime : +airedOn dynamic
Anime : +releasedOn dynamic
Anime : +props List~Object?~
Equatable <|-- Anime

class Seyu
Seyu : +id int
Seyu : +name String
Seyu : +russian String
Seyu : +image Image
Seyu o-- Image
Seyu : +url String
Seyu : +props List~Object?~
Equatable <|-- Seyu

class Image
Image : +original String
Image : +preview String
Image : +x96 String
Image : +x48 String
Image : +props List~Object?~
Equatable <|-- Image

class Manga
Manga : +id int
Manga : +name String
Manga : +russian String
Manga : +image Image
Manga o-- Image
Manga : +url String
Manga : +kind String
Manga : +score String
Manga : +status String
Manga : +episodes int
Manga : +episodesAired int
Manga : +airedOn dynamic
Manga : +releasedOn dynamic
Manga : +props List~Object?~
Equatable <|-- Manga

class Creditional
Creditional : +id int
Creditional : +nickname String
Creditional : +avatar String
Creditional : +image Image
Creditional o-- Image
Creditional : +lastOnlineAt DateTime
Creditional : +url String
Creditional : +name dynamic
Creditional : +sex String
Creditional : +website String
Creditional : +birthOn dynamic
Creditional : +fullYears int
Creditional : +locale String
Creditional : +props List~Object?~
Equatable <|-- Creditional

class Image
Image : +x160 String
Image : +x148 String
Image : +x80 String
Image : +x64 String
Image : +x48 String
Image : +x32 String
Image : +x16 String
Image : +props List~Object?~
Equatable <|-- Image

class Image
Image : +original String?
Image : +preview String?
Image : +x96 String?
Image : +x48 String?
Image : +props List~Object?~
Equatable <|-- Image

class Manga
Manga : +id int?
Manga : +name String?
Manga : +russian String?
Manga : +image Image?
Manga o-- Image
Manga : +url String?
Manga : +kind String?
Manga : +score String?
Manga : +status String?
Manga : +volumes int?
Manga : +chapters int?
Manga : +airedOn DateTime?
Manga : +releasedOn dynamic
Manga : +props List~Object?~
Equatable <|-- Manga

class MangaDetails
MangaDetails : +id int?
MangaDetails : +name String?
MangaDetails : +russian String?
MangaDetails : +image Image?
MangaDetails o-- Image
MangaDetails : +url String?
MangaDetails : +kind String?
MangaDetails : +score String?
MangaDetails : +status String?
MangaDetails : +volumes int?
MangaDetails : +chapters int?
MangaDetails : +airedOn DateTime?
MangaDetails : +releasedOn DateTime?
MangaDetails : +english List~String~?
MangaDetails : +japanese List~String~?
MangaDetails : +synonyms List~dynamic~?
MangaDetails : +licenseNameRu String?
MangaDetails : +description String?
MangaDetails : +descriptionHtml String?
MangaDetails : +descriptionSource dynamic
MangaDetails : +franchise String?
MangaDetails : +favoured bool?
MangaDetails : +anons bool?
MangaDetails : +ongoing bool?
MangaDetails : +threadId int?
MangaDetails : +topicId int?
MangaDetails : +myanimelistId int?
MangaDetails : +ratesScoresStats List~RatesScoresStat~?
MangaDetails : +ratesStatusesStats List~RatesStatusesStat~?
MangaDetails : +licensors List~String~?
MangaDetails : +genres List~Genre~?
MangaDetails : +publishers List~Publisher~?
MangaDetails : +userRate dynamic
MangaDetails : +props List~Object?~
Equatable <|-- MangaDetails

class Genre
Genre : +id int?
Genre : +name String?
Genre : +russian String?
Genre : +kind String?
Genre : +props List~Object?~
Equatable <|-- Genre

class Image
Image : +original String?
Image : +preview String?
Image : +x96 String?
Image : +x48 String?
Image : +props List~Object?~
Equatable <|-- Image

class Publisher
Publisher : +id int?
Publisher : +name String?
Publisher : +props List~Object?~
Equatable <|-- Publisher

class RatesScoresStat
RatesScoresStat : +name int?
RatesScoresStat : +value int?
RatesScoresStat : +props List~Object?~
Equatable <|-- RatesScoresStat

class RatesStatusesStat
RatesStatusesStat : +name String?
RatesStatusesStat : +value int?
RatesStatusesStat : +props List~Object?~
Equatable <|-- RatesStatusesStat

class Related
Related : +relation String?
Related : +relationRussian String?
Related : +anime Anime?
Related o-- Anime
Related : +manga Manga?
Related o-- Manga
Related : +props List~Object?~
Equatable <|-- Related

class UserAuth
UserAuth : +accessToken String?
UserAuth : +tokenType String?
UserAuth : +expireIn int?
UserAuth : +refreshToken String?
UserAuth : +scope String?
UserAuth : +createdAt int?
UserAuth : +props List~Object?~
Equatable <|-- UserAuth

class UserRate
UserRate : +id int
UserRate : +userId int
UserRate : +targetId int
UserRate : +targetType String
UserRate : +score int
UserRate : +status String
UserRate : +rewatches int
UserRate : +episodes int
UserRate : +volumes int
UserRate : +chapters int
UserRate : +text String?
UserRate : +textHtml String
UserRate : +createdAt DateTime
UserRate : +updatedAt DateTime
UserRate : +props List~Object?~
Equatable <|-- UserRate

class GetAccessTokenRepository
<<abstract>> GetAccessTokenRepository
GetAccessTokenRepository : +getAccessToken()* dynamic

class AnimeRepository
<<abstract>> AnimeRepository
AnimeRepository : +getAnimes()* dynamic
AnimeRepository : +getAnimesByName()* dynamic
AnimeRepository : +getAnimeById()* dynamic
AnimeRepository : +getVideos()* dynamic
AnimeRepository : +getScreenshots()* dynamic

class CharacterRepository
<<abstract>> CharacterRepository
CharacterRepository : +getCharacterById()* dynamic

class CreditionalRepository
<<abstract>> CreditionalRepository
CreditionalRepository : +getCreditionals()* dynamic

class MangaRepository
<<abstract>> MangaRepository
MangaRepository : +getMangas()* dynamic
MangaRepository : +getMangaById()* dynamic
MangaRepository : +getRelatedMangas()* dynamic

class RefreshAccessTokenRepository
<<abstract>> RefreshAccessTokenRepository
RefreshAccessTokenRepository : +refreshAccessToken()* dynamic

class RelatedRepository
<<abstract>> RelatedRepository
RelatedRepository : +getRelated()* dynamic

class SaveAccessTokenRepository
<<abstract>> SaveAccessTokenRepository
SaveAccessTokenRepository : +saveAccessToken()* dynamic

class SaveRefreshTokenRepository
<<abstract>> SaveRefreshTokenRepository
SaveRefreshTokenRepository : +saveRefreshToken()* dynamic

class UserRateRepository
<<abstract>> UserRateRepository
UserRateRepository : +getUserRates()* dynamic
UserRateRepository : +addAnimeInUserRates()* dynamic

class GetAccessToken
GetAccessToken : +userGetAccessTokenRepository GetAccessTokenRepository
GetAccessToken o-- GetAccessTokenRepository
GetAccessToken : +call() dynamic
UseCase <|-- GetAccessToken

class GetAccessTokenParams
GetAccessTokenParams : +grantType String
GetAccessTokenParams : +identifier String
GetAccessTokenParams : +secret String
GetAccessTokenParams : +code String
GetAccessTokenParams : +redirectUri Uri
GetAccessTokenParams : +props List~Object?~
Equatable <|-- GetAccessTokenParams

class RefreshAccessToken
RefreshAccessToken : +refreshAccessTokenRepository RefreshAccessTokenRepository
RefreshAccessToken o-- RefreshAccessTokenRepository
RefreshAccessToken : +call() dynamic
UseCase <|-- RefreshAccessToken

class RefreshAccessTokenParams
RefreshAccessTokenParams : +grantType String
RefreshAccessTokenParams : +identifier String
RefreshAccessTokenParams : +secret String
RefreshAccessTokenParams : +refreshToken String
RefreshAccessTokenParams : +props List~Object?~
Equatable <|-- RefreshAccessTokenParams

class GetAnimes
GetAnimes : +animeRepository AnimeRepository
GetAnimes o-- AnimeRepository
GetAnimes : +call() dynamic
UseCase <|-- GetAnimes

class GetAnimesParams
GetAnimesParams : +page int
GetAnimesParams : +order String?
GetAnimesParams : +limit int?
GetAnimesParams : +score int?
GetAnimesParams : +props List~Object?~
Equatable <|-- GetAnimesParams

class GetAnimeById
GetAnimeById : +animeRepository AnimeRepository
GetAnimeById o-- AnimeRepository
GetAnimeById : +call() dynamic
UseCase <|-- GetAnimeById

class GetAnimeByIdParams
GetAnimeByIdParams : +id int
GetAnimeByIdParams : +props List~Object?~
Equatable <|-- GetAnimeByIdParams

class GetAnimeByName
GetAnimeByName : +animeRepository AnimeRepository
GetAnimeByName o-- AnimeRepository
GetAnimeByName : +call() dynamic
UseCase <|-- GetAnimeByName

class GetAnimesByNameParams
GetAnimesByNameParams : +phrase String
GetAnimesByNameParams : +limit int?
GetAnimesByNameParams : +props List~Object?~
Equatable <|-- GetAnimesByNameParams

class GetRelatedAnimes
GetRelatedAnimes : +relatedRepository RelatedRepository
GetRelatedAnimes o-- RelatedRepository
GetRelatedAnimes : +call() dynamic
UseCase <|-- GetRelatedAnimes

class GetRelatedParams
GetRelatedParams : +id int
GetRelatedParams : +props List~Object?~
Equatable <|-- GetRelatedParams

class GetScreenshots
GetScreenshots : +animeRepository AnimeRepository
GetScreenshots o-- AnimeRepository
GetScreenshots : +call() dynamic
UseCase <|-- GetScreenshots

class GetScreenshotsParams
GetScreenshotsParams : +id int
GetScreenshotsParams : +props List~Object?~
Equatable <|-- GetScreenshotsParams

class GetVideos
GetVideos : +animeRepository AnimeRepository
GetVideos o-- AnimeRepository
GetVideos : +call() dynamic
UseCase <|-- GetVideos

class GetVideosParams
GetVideosParams : +id int
GetVideosParams : +props List~Object?~
Equatable <|-- GetVideosParams

class GetCharacterById
GetCharacterById : +characterRepository CharacterRepository
GetCharacterById o-- CharacterRepository
GetCharacterById : +call() dynamic
UseCase <|-- GetCharacterById

class GetCharacterByIdParams
GetCharacterByIdParams : +id int
GetCharacterByIdParams : +props List~Object?~
Equatable <|-- GetCharacterByIdParams

class GetCreditional
GetCreditional : +creditionalRepository CreditionalRepository
GetCreditional o-- CreditionalRepository
GetCreditional : +call() dynamic
UseCase <|-- GetCreditional

class GetCreditionalParams
GetCreditionalParams : +accessToken String
GetCreditionalParams : +props List~Object?~
Equatable <|-- GetCreditionalParams

class GetMangas
GetMangas : +mangaRepository MangaRepository
GetMangas o-- MangaRepository
GetMangas : +call() dynamic
UseCase <|-- GetMangas

class GetMangasParams
GetMangasParams : +page int
GetMangasParams : +order String?
GetMangasParams : +limit int?
GetMangasParams : +score int?
GetMangasParams : +props List~Object?~
Equatable <|-- GetMangasParams

class GetAnimeById
GetAnimeById : +animeRepository AnimeRepository
GetAnimeById o-- AnimeRepository
GetAnimeById : +call() dynamic
UseCase <|-- GetAnimeById

class GetAnimeByIdParams
GetAnimeByIdParams : +id int
GetAnimeByIdParams : +props List~Object?~
Equatable <|-- GetAnimeByIdParams

class SaveAccessToken
SaveAccessToken : +saveAccessTokenRepository SaveAccessTokenRepository
SaveAccessToken o-- SaveAccessTokenRepository
SaveAccessToken : +call() dynamic
UseCase <|-- SaveAccessToken

class SaveAccessTokenParams
SaveAccessTokenParams : +accessToken String
SaveAccessTokenParams : +props List~Object?~
Equatable <|-- SaveAccessTokenParams

class SaveRefreshToken
SaveRefreshToken : +saveRefreshTokenRepository SaveRefreshTokenRepository
SaveRefreshToken o-- SaveRefreshTokenRepository
SaveRefreshToken : +call() dynamic
UseCase <|-- SaveRefreshToken

class SaveRefreshTokenParams
SaveRefreshTokenParams : +refreshToken String
SaveRefreshTokenParams : +props List~Object?~
Equatable <|-- SaveRefreshTokenParams

class AddAnimeInUserRates
AddAnimeInUserRates : +userRateRepository UserRateRepository
AddAnimeInUserRates o-- UserRateRepository
AddAnimeInUserRates : +call() dynamic
UseCase <|-- AddAnimeInUserRates

class AddAnimeInUserRatesParams
AddAnimeInUserRatesParams : +userRate UserRate
AddAnimeInUserRatesParams o-- UserRate
AddAnimeInUserRatesParams : +props List~Object?~
Equatable <|-- AddAnimeInUserRatesParams

class GetUserRate
GetUserRate : +userRateRepository UserRateRepository
GetUserRate o-- UserRateRepository
GetUserRate : +call() dynamic
UseCase <|-- GetUserRate

class GetUserRateParams
GetUserRateParams : +id int
GetUserRateParams : +props List~Object?~
Equatable <|-- GetUserRateParams

class AnimeDetailCubit
AnimeDetailCubit : +getAnimeById GetAnimeById
AnimeDetailCubit o-- GetAnimeById
AnimeDetailCubit : +getRelatedAnimes GetRelatedAnimes
AnimeDetailCubit o-- GetRelatedAnimes
AnimeDetailCubit : +getAnimeDetails() dynamic
AnimeDetailCubit : -_getRelatedAnimes() dynamic
Cubit <|-- AnimeDetailCubit

class AnimeDetailState
<<abstract>> AnimeDetailState

class AnimeDetailLoaded
AnimeDetailLoaded : +animeDetails AnimeDetails
AnimeDetailLoaded o-- AnimeDetails
AnimeDetailLoaded : +related List~Related~
AnimeDetailState <|-- AnimeDetailLoaded

class AnimeDetailError
AnimeDetailError : +errorMessage String
AnimeDetailState <|-- AnimeDetailError

class AnimeDetailEmpty
AnimeDetailState <|-- AnimeDetailEmpty

class ScreenshotsCubit
ScreenshotsCubit : +getScreenshots GetScreenshots
ScreenshotsCubit o-- GetScreenshots
ScreenshotsCubit : +getAllScreenshots() dynamic
Cubit <|-- ScreenshotsCubit

class ScreenshotsState
<<abstract>> ScreenshotsState
ScreenshotsState : +props List~Object~
Equatable <|-- ScreenshotsState

class ScreenshotsEmpty
ScreenshotsState <|-- ScreenshotsEmpty

class ScreenshotsError
ScreenshotsError : +errorMessage String
ScreenshotsState <|-- ScreenshotsError

class ScreenshotsLoaded
ScreenshotsLoaded : +screenshots List~Screenshot~
ScreenshotsState <|-- ScreenshotsLoaded

class VideosCubit
VideosCubit : +getVideos GetVideos
VideosCubit o-- GetVideos
VideosCubit : +getAllVideos() dynamic
Cubit <|-- VideosCubit

class VideosState
<<abstract>> VideosState
VideosState : +props List~Object~
Equatable <|-- VideosState

class VideosEmpty
VideosState <|-- VideosEmpty

class VideosError
VideosError : +errorMessage String
VideosState <|-- VideosError

class VideosLoaded
VideosLoaded : +videos List~Video~
VideosState <|-- VideosLoaded

class AnimeDetailScreen
AnimeDetailScreen : +id int
AnimeDetailScreen : +createState() State<AnimeDetailScreen>
StatefulWidget <|-- AnimeDetailScreen

class _AnimeDetailScreenState
_AnimeDetailScreenState : +initState() void
_AnimeDetailScreenState : +build() Widget
State <|-- _AnimeDetailScreenState

class TopWidget
TopWidget : +animeDetails AnimeDetails
TopWidget o-- AnimeDetails
TopWidget : +build() Widget
StatelessWidget <|-- TopWidget

class InformationWidget
InformationWidget : +animeDetails AnimeDetails
InformationWidget o-- AnimeDetails
InformationWidget : +build() Widget
StatelessWidget <|-- InformationWidget

class DescriptionWidget
DescriptionWidget : +animeDetails AnimeDetails
DescriptionWidget o-- AnimeDetails
DescriptionWidget : +build() Widget
StatelessWidget <|-- DescriptionWidget

class ScreenshotsWidget
ScreenshotsWidget : +animeDetails AnimeDetails
ScreenshotsWidget o-- AnimeDetails
ScreenshotsWidget : +build() Widget
StatelessWidget <|-- ScreenshotsWidget

class VideosButton
VideosButton : +animeDetails AnimeDetails
VideosButton o-- AnimeDetails
VideosButton : +build() Widget
StatelessWidget <|-- VideosButton

class RelatedWidget
RelatedWidget : +relateds List~Related~
RelatedWidget : +build() Widget
StatelessWidget <|-- RelatedWidget

class _AnimeCard
_AnimeCard : +anime Anime
_AnimeCard o-- Anime
_AnimeCard : +build() Widget
StatelessWidget <|-- _AnimeCard

class _MangaCard
_MangaCard : +manga Manga
_MangaCard o-- Manga
_MangaCard : +build() Widget
StatelessWidget <|-- _MangaCard

class ScreenshotsPage
ScreenshotsPage : +id int
ScreenshotsPage : +createState() State<ScreenshotsPage>
StatefulWidget <|-- ScreenshotsPage

class _ScreenshotsPageState
_ScreenshotsPageState : +initState() void
_ScreenshotsPageState : +build() Widget
State <|-- _ScreenshotsPageState

class VideosPage
VideosPage : +id int
VideosPage : +createState() State<VideosPage>
StatefulWidget <|-- VideosPage

class _VideosPageState
_VideosPageState : +initState() void
_VideosPageState : +build() Widget
State <|-- _VideosPageState

class CharacterCubit
CharacterCubit : +getCharacterById GetCharacterById
CharacterCubit o-- GetCharacterById
CharacterCubit : +getCharacter() dynamic
Cubit <|-- CharacterCubit

class CharacterState
<<abstract>> CharacterState
CharacterState : +props List~Object~
Equatable <|-- CharacterState

class CharacterEmpty
CharacterState <|-- CharacterEmpty

class CharacterError
CharacterError : +errorMessage String
CharacterState <|-- CharacterError

class CharacterLoaded
CharacterLoaded : +character Character
CharacterLoaded o-- Character
CharacterState <|-- CharacterLoaded

class CharacterScreen
CharacterScreen : +id int
CharacterScreen : +createState() State<CharacterScreen>
StatefulWidget <|-- CharacterScreen

class _CharacterScreenState
_CharacterScreenState : +initState() void
_CharacterScreenState : +build() Widget
State <|-- _CharacterScreenState

class CharacterNameWidget
CharacterNameWidget : +title String
CharacterNameWidget : +name String
CharacterNameWidget : +build() Widget
StatelessWidget <|-- CharacterNameWidget

class AnimePageCubit
AnimePageCubit : +getAnimes GetAnimes
AnimePageCubit o-- GetAnimes
AnimePageCubit : +animes List~Anime~
AnimePageCubit : +getAnimeList() dynamic
Cubit <|-- AnimePageCubit

class AnimePageState
<<abstract>> AnimePageState
AnimePageState : +props List~Object~
Equatable <|-- AnimePageState

class AnimePageLoaded
AnimePageLoaded : +animeList List~Anime~
AnimePageState <|-- AnimePageLoaded

class AnimePageEmpty
AnimePageState <|-- AnimePageEmpty

class AnimePageLoading
AnimePageState <|-- AnimePageLoading

class AnimePageError
AnimePageError : +errorMessage String
AnimePageState <|-- AnimePageError

class ProfileCubit
ProfileCubit : +getCreditional GetCreditional
ProfileCubit o-- GetCreditional
ProfileCubit : +getCreditionals() dynamic
Cubit <|-- ProfileCubit

class ProfileState
<<abstract>> ProfileState

class ProfileInitial
ProfileInitial : +creditional Creditional
ProfileInitial o-- Creditional
ProfileState <|-- ProfileInitial

class ProfileEmpty
ProfileState <|-- ProfileEmpty

class ProfileTokenException
ProfileState <|-- ProfileTokenException

class MangaPageCubit
MangaPageCubit : +getMangas GetMangas
MangaPageCubit o-- GetMangas
MangaPageCubit : +getAllMangas() dynamic
Cubit <|-- MangaPageCubit

class MangaPageState
<<abstract>> MangaPageState
MangaPageState : +props List~Object~
Equatable <|-- MangaPageState

class MangaPageEmpty
MangaPageState <|-- MangaPageEmpty

class MangaPageError
MangaPageError : +errorMessage String
MangaPageState <|-- MangaPageError

class MangaPageLoaded
MangaPageLoaded : +mangaList List~Manga~
MangaPageState <|-- MangaPageLoaded

class MangaPageLoading
MangaPageState <|-- MangaPageLoading

class HomeScreen
HomeScreen : +createState() State<HomeScreen>
StatefulWidget <|-- HomeScreen

class _HomeScreenState
_HomeScreenState : -_pageController PageController
_HomeScreenState o-- PageController
_HomeScreenState : -_page int
_HomeScreenState : -_position double?
_HomeScreenState : +drawerItems List~dynamic~
_HomeScreenState : +selectedRadioTile int
_HomeScreenState : +orderVariants List~String~
_HomeScreenState : +build() Widget
_HomeScreenState : +filterModalBotomSheet() void
_HomeScreenState : +navigationTapped() void
_HomeScreenState : +initState() void
_HomeScreenState : -_getScrollPosition() void
_HomeScreenState : +dispose() void
_HomeScreenState : -_onPageChanged() void
State <|-- _HomeScreenState

class AnimeLoadedWidget
AnimeLoadedWidget : -_controller ScrollController
AnimeLoadedWidget o-- ScrollController
AnimeLoadedWidget : +animes List~Anime~
AnimeLoadedWidget : +build() Widget
StatelessWidget <|-- AnimeLoadedWidget

class AnimeScreenBuilder
AnimeScreenBuilder : +position double?
AnimeScreenBuilder : +order String
AnimeScreenBuilder : +createState() State<AnimeScreenBuilder>
StatefulWidget <|-- AnimeScreenBuilder

class _AnimeScreenBuilderState
_AnimeScreenBuilderState : +scrollPosition double?
_AnimeScreenBuilderState : -_scrollController ScrollController
_AnimeScreenBuilderState o-- ScrollController
_AnimeScreenBuilderState : +animes List~Anime~
_AnimeScreenBuilderState : +animeListPage int
_AnimeScreenBuilderState : +initState() void
_AnimeScreenBuilderState : +dispose() void
_AnimeScreenBuilderState : -_scrollListener() void
_AnimeScreenBuilderState : +build() Widget
State <|-- _AnimeScreenBuilderState

class EmptyWidget
EmptyWidget : +build() Widget
StatelessWidget <|-- EmptyWidget

class HomeNavDrawer
HomeNavDrawer : +drawerItems List~dynamic~
HomeNavDrawer : -_page int
HomeNavDrawer : -_controller PageController
HomeNavDrawer o-- PageController
HomeNavDrawer : +createState() State<HomeNavDrawer>
StatefulWidget <|-- HomeNavDrawer

class _HomeNavDrawerState
_HomeNavDrawerState : +initState() void
_HomeNavDrawerState : +build() Widget
State <|-- _HomeNavDrawerState

class MangaLoadedWidget
MangaLoadedWidget : -_controller ScrollController
MangaLoadedWidget o-- ScrollController
MangaLoadedWidget : +animes List~Anime~
MangaLoadedWidget : +build() Widget
StatelessWidget <|-- MangaLoadedWidget

class LoginScreenCubit
LoginScreenCubit : +getAccessToken GetAccessToken
LoginScreenCubit o-- GetAccessToken
LoginScreenCubit : +saveAccessToken SaveAccessToken
LoginScreenCubit o-- SaveAccessToken
LoginScreenCubit : +saveRefreshToken SaveRefreshToken
LoginScreenCubit o-- SaveRefreshToken
LoginScreenCubit : +login() void
LoginScreenCubit : +checkTokensExist() dynamic
Cubit <|-- LoginScreenCubit

class LoginScreenState
<<abstract>> LoginScreenState
LoginScreenState : +props List~Object~
Equatable <|-- LoginScreenState

class LoginScreenEmpty
LoginScreenState <|-- LoginScreenEmpty

class LoginScreenLoaded
LoginScreenState <|-- LoginScreenLoaded

class LoginScreen
LoginScreen : +createState() State<LoginScreen>
StatefulWidget <|-- LoginScreen

class _LoginScreenState
_LoginScreenState : +initState() void
_LoginScreenState : +build() Widget
State <|-- _LoginScreenState

class LoginButton
LoginButton : +onTap dynamic Function
LoginButton o-- dynamic Function
LoginButton : +build() Widget
StatelessWidget <|-- LoginButton

class SearchBloc
SearchBloc : -_getAnimeByName GetAnimeByName
SearchBloc o-- GetAnimeByName
SearchBloc : -_previousQuery String
SearchBloc : -_animeSearch() dynamic
Bloc <|-- SearchBloc

class SearchEvent
<<abstract>> SearchEvent
SearchEvent : +props List~Object~
Equatable <|-- SearchEvent

class SearchAnimeEvent
SearchAnimeEvent : +query String
SearchEvent <|-- SearchAnimeEvent

class SearchState
<<abstract>> SearchState
SearchState : +props List~Object~
Equatable <|-- SearchState

class SearchLoaded
SearchLoaded : +animes List~Anime~
SearchState <|-- SearchLoaded

class SearchEmpty
SearchState <|-- SearchEmpty

class SearchError
SearchError : +errorMessage String
SearchState <|-- SearchError

class MyApp
MyApp : +build() Widget
StatelessWidget <|-- MyApp
